namespace UniGetUI.Core.SettingsEngine;

public static partial class Settings
{
    public enum K
    {
        EnableProxy,
        EnableProxyAuth,
        DisableWaitForInternetConnection,
        IconDataBaseURL,
        DisableLangAutoUpdater,
        DisableDMWThreadOptimizations,
        DisableTelemetry,
        DisableTimeoutOnPackageListingTasks,
        RemoveAllDesktopShortcuts,
        EnableScoopCleanup,
        EnableScoopCleanupCache,
        EnableScoopCleanupApps,
        IgnoreUpdatesNotApplicable,
        DisableNewWinGetTroubleshooter,
        DisableUpdateVcpkgGitPorts,
        DisableSelectingUpdatesByDefault,
        DisableAutoCheckforUpdates,
        AskToDeleteNewDesktopShortcuts,
        AskAboutNewStartMenuShortcuts,
        DoCacheAdminRights,
        DoCacheAdminRightsForBatches,
        DisableAutoUpdateWingetUI,
        EnableUniGetUIBeta,
        ShowVersionNumberOnTitlebar,
        TransferredOldSettings,
        DisableApi,
        DisableSystemTray,
        MaintainSuccessfulInstalls,
        AutomaticallyUpdatePackages,
        DisableAUPOnMeteredConnections,
        DisableAUPOnBatterySaver,
        DisableAUPOnBattery,
        CustomVcpkgRoot,
        AlreadyWarnedAboutAdmin,
        AlreadyWarnedAboutChocolateyMigration,
        ShownTelemetryBanner,
        CollapseNavMenuOnWideScreen,
        NavMenuMode,
        EnablePackageBackup_LOCAL,
        EnablePackageBackup_CLOUD,
        ChangeBackupOutputDirectory,
        DisableWinGetMalfunctionDetector,
        EnableBackupTimestamping,
        DisableIconsOnPackageLists,
        DisablePackageIllustrations,
        ProxyURL,
        ProxyUsername,
        PreferredLanguage,
        DefaultVcpkgTriplet,
        UpdatesCheckInterval,
        ParallelOperationCount,
        TelemetryClientToken,
        PreferredTheme,
        StartupPage,
        WindowGeometry,
        IgnoredUpdatesWindowSize,
        ChangeBackupFileName,
        MaxLocalBackupCount,
        MaxLocalBackupCountCustom,
        KnownLocalBackupNames,
        CurrentSessionToken,
        IgnoredPackageUpdates,
        AutoUpdatedPackages,
        AutoUpdatedPackagesImported,
        DisabledManagers,
        DeletableDesktopShortcuts,
        StartMenuShortcutFolders,
        DeletableStartMenuShortcuts,
        RelocatedStartMenuShortcuts,
        WinGetAlreadyUpgradedPackages,
        WinGetUpgradeAttempts,
        WinGetStuckUpgradeThreshold,
        DependencyManagement,
        DisabledPackageManagerNotifications,
        PackageListViewMode,
        DisableInstantSearch,
        SidepanelWidths,
        HideToggleFilters,
        PackageListSortFieldIndex,
        PackageListSortDescending,
        FreshBoolSetting,
        FreshValue,
        DisableNotifications,
        DisableUpdatesNotifications,
        DisableErrorNotifications,
        DisableSuccessNotifications,
        DisableProgressNotifications,
        ShowOperationSummaryNotifications,
        KillProcessesThatRefuseToDie,
        ManagerPaths,
        GitHubUserLogin,
        DisableNewProcessLineHandler,
        InstallInstalledPackagesBundlesPage,
        ProhibitElevation,
        DisableIntegrityChecks,
        UseLegacyElevator,
        WinGetForceLocationOnUpdate,
        ExpandEnvVarsWithPercentSyntax,
        MinimumUpdateAge,
        MinimumUpdateAgeCustom,
        PerManagerMinimumUpdateAge,
        PerManagerMinimumUpdateAgeCustom,
        WinGetCliToolPreference,
        WinGetComApiPolicy,
        WinGetDownloadFullManifest,
        InstallerFileNameScheme,
        DisableInstallerHostChangeWarning,
        ShowInstallerHostColumn,
        BunPreferLatestVersions,
        RedactUsernameInLog,
        DisableReleaseNotesOnUpdate,
        LastKnownBuildNumber,
        DisableAutoSoftwareRenderingOnGpuLessHosts,
        UseSystemUIFont,
        MaintenanceSchedules,
        MaintenanceTaskLastRun,
        MaintenanceTaskLastFailure,
        // NOTE: Set this to true to delegate package operations to Devolutions Agent broker
        // instead of using local UAC elevation. Change default here when ready for production.
        UseAgentBroker,

        Test1,
        Test2,
        Test3,
        Test4,
        Test5,
        Test6,
        Test7_Legacy,
        Unset,
    };

    public static string ResolveKey(K key)
    {
        return key switch
        {
            K.EnableProxy => "EnableProxy",
            K.EnableProxyAuth => "EnableProxyAuth",
            K.DisableWaitForInternetConnection => "DisableWaitForInternetConnection",
            K.IconDataBaseURL => "IconDataBaseURL",
            K.DisableLangAutoUpdater => "DisableLangAutoUpdater",
            K.DisableDMWThreadOptimizations => "DisableDMWThreadOptimizations",
            K.DisableTelemetry => "DisableTelemetry",
            K.DisableTimeoutOnPackageListingTasks => "DisableTimeoutOnPackageListingTasks",
            K.RemoveAllDesktopShortcuts => "RemoveAllDesktopShortcuts",
            K.EnableScoopCleanup => "EnableScoopCleanup",
            K.EnableScoopCleanupCache => "EnableScoopCleanupCache",
            K.EnableScoopCleanupApps => "EnableScoopCleanupApps",
            K.IgnoreUpdatesNotApplicable => "IgnoreUpdatesNotApplicable",
            K.DisableNewWinGetTroubleshooter => "DisableNewWinGetTroubleshooter",
            K.DisableUpdateVcpkgGitPorts => "DisableUpdateVcpkgGitPorts",
            K.DisableSelectingUpdatesByDefault => "DisableSelectingUpdatesByDefault",
            K.DisableAutoCheckforUpdates => "DisableAutoCheckforUpdates",
            K.AskToDeleteNewDesktopShortcuts => "AskToDeleteNewDesktopShortcuts",
            K.AskAboutNewStartMenuShortcuts => "AskAboutNewStartMenuShortcuts",
            K.DoCacheAdminRights => "DoCacheAdminRights",
            K.DoCacheAdminRightsForBatches => "DoCacheAdminRightsForBatches",
            K.DisableAutoUpdateWingetUI => "DisableAutoUpdateWingetUI",
            K.EnableUniGetUIBeta => "EnableUniGetUIBeta",
            K.ShowVersionNumberOnTitlebar => "ShowVersionNumberOnTitlebar",
            K.TransferredOldSettings => "TransferredOldSettings",
            K.DisableApi => "DisableApi",
            K.DisableSystemTray => "DisableSystemTray",
            K.MaintainSuccessfulInstalls => "MaintainSuccessfulInstalls",
            K.AutomaticallyUpdatePackages => "AutomaticallyUpdatePackages",
            K.DisableAUPOnMeteredConnections => "DisableAUPOnMeteredConnections",
            K.DisableAUPOnBatterySaver => "DisableAUPOnBatterySaver",
            K.DisableAUPOnBattery => "DisableAUPOnBattery",
            K.CustomVcpkgRoot => "CustomVcpkgRoot",
            K.AlreadyWarnedAboutAdmin => "AlreadyWarnedAboutAdmin",
            K.AlreadyWarnedAboutChocolateyMigration => "AlreadyWarnedAboutChocolateyMigration",
            K.ShownTelemetryBanner => "ShownTelemetryBanner",
            K.CollapseNavMenuOnWideScreen => "CollapseNavMenuOnWideScreen",
            K.NavMenuMode => "NavMenuMode",
            K.EnablePackageBackup_LOCAL => "EnablePackageBackup",
            K.EnablePackageBackup_CLOUD => "EnablePackageBackup_CLOUD",
            K.ChangeBackupOutputDirectory => "ChangeBackupOutputDirectory",
            K.DisableWinGetMalfunctionDetector => "DisableWinGetMalfunctionDetector",
            K.EnableBackupTimestamping => "EnableBackupTimestamping",
            K.DisableIconsOnPackageLists => "DisableIconsOnPackageLists",
            K.DisablePackageIllustrations => "DisablePackageIllustrations",
            K.ProxyURL => "ProxyURL",
            K.ProxyUsername => "ProxyUsername",
            K.PreferredLanguage => "PreferredLanguage",
            K.DefaultVcpkgTriplet => "DefaultVcpkgTriplet",
            K.UpdatesCheckInterval => "UpdatesCheckInterval",
            K.ParallelOperationCount => "ParallelOperationCount",
            K.TelemetryClientToken => "TelemetryClientToken",
            K.PreferredTheme => "PreferredTheme",
            K.StartupPage => "StartupPage",
            K.WindowGeometry => "WindowGeometry",
            K.IgnoredUpdatesWindowSize => "IgnoredUpdatesWindowSize",
            K.ChangeBackupFileName => "ChangeBackupFileName",
            K.MaxLocalBackupCount => "MaxLocalBackupCount",
            K.MaxLocalBackupCountCustom => "MaxLocalBackupCountCustom",
            K.KnownLocalBackupNames => "KnownLocalBackupNames",
            K.CurrentSessionToken => "CurrentSessionToken",
            K.IgnoredPackageUpdates => "IgnoredPackageUpdates",
            K.AutoUpdatedPackages => "AutoUpdatedPackages",
            K.AutoUpdatedPackagesImported => "AutoUpdatedPackagesImported",
            K.DisabledManagers => "DisabledManagers",
            K.DeletableDesktopShortcuts => "DeletableDesktopShortcuts",
            K.StartMenuShortcutFolders => "StartMenuShortcutFolders",
            K.DeletableStartMenuShortcuts => "DeletableStartMenuShortcuts",
            K.RelocatedStartMenuShortcuts => "RelocatedStartMenuShortcuts",
            K.WinGetAlreadyUpgradedPackages => "WinGetAlreadyUpgradedPackages",
            K.WinGetUpgradeAttempts => "WinGetUpgradeAttempts",
            K.WinGetStuckUpgradeThreshold => "WinGetStuckUpgradeThreshold",
            K.DependencyManagement => "DependencyManagement",
            K.DisabledPackageManagerNotifications => "DisabledPackageManagerNotifications",
            K.PackageListViewMode => "PackageListViewMode",
            K.DisableInstantSearch => "DisableInstantSearch",
            K.SidepanelWidths => "SidepanelWidths",
            K.HideToggleFilters => "HideToggleFilters",
            K.PackageListSortFieldIndex => "PackageListSortFieldIndex",
            K.PackageListSortDescending => "PackageListSortDescending",
            K.FreshBoolSetting => "FreshBoolSetting",
            K.FreshValue => "FreshValue",
            K.DisableNotifications => "DisableNotifications",
            K.DisableUpdatesNotifications => "DisableUpdatesNotifications",
            K.DisableErrorNotifications => "DisableErrorNotifications",
            K.DisableSuccessNotifications => "DisableSuccessNotifications",
            K.DisableProgressNotifications => "DisableProgressNotifications",
            K.ShowOperationSummaryNotifications => "ShowOperationSummaryNotifications",
            K.KillProcessesThatRefuseToDie => "KillProcessesThatRefuseToDie",
            K.ManagerPaths => "ManagerPaths",
            K.GitHubUserLogin => "GitHubUserLogin",
            K.DisableNewProcessLineHandler => "DisableNewProcessLineHandler",
            K.InstallInstalledPackagesBundlesPage => "InstallInstalledPackagesBundlesPage",
            K.ProhibitElevation => "ProhibitElevation",
            K.DisableIntegrityChecks => "DisableIntegrityChecks",
            K.UseLegacyElevator => "UseLegacyElevator",
            K.WinGetForceLocationOnUpdate => "WinGetForceLocationOnUpdate",
            K.ExpandEnvVarsWithPercentSyntax => "ExpandEnvVarsWithPercentSyntax",
            K.MinimumUpdateAge => "MinimumUpdateAge",
            K.MinimumUpdateAgeCustom => "MinimumUpdateAgeCustom",
            K.PerManagerMinimumUpdateAge => "PerManagerMinimumUpdateAge",
            K.PerManagerMinimumUpdateAgeCustom => "PerManagerMinimumUpdateAgeCustom",
            K.WinGetCliToolPreference => "WinGetCliToolPreference",
            K.WinGetComApiPolicy => "WinGetComApiPolicy",
            K.WinGetDownloadFullManifest => "WinGetDownloadFullManifest",
            K.InstallerFileNameScheme => "InstallerFileNameScheme",
            K.DisableInstallerHostChangeWarning => "DisableInstallerHostChangeWarning",
            K.ShowInstallerHostColumn => "ShowInstallerHostColumn",
            K.BunPreferLatestVersions => "BunPreferLatestVersions",
            K.RedactUsernameInLog => "RedactUsernameInLog",
            K.DisableReleaseNotesOnUpdate => "DisableReleaseNotesOnUpdate",
            K.LastKnownBuildNumber => "LastKnownBuildNumber",
            K.DisableAutoSoftwareRenderingOnGpuLessHosts => "DisableAutoSoftwareRenderingOnGpuLessHosts",
            K.UseSystemUIFont => "UseSystemUIFont",
            K.MaintenanceSchedules => "MaintenanceSchedules",
            K.MaintenanceTaskLastRun => "MaintenanceTaskLastRun",
            K.MaintenanceTaskLastFailure => "MaintenanceTaskLastFailure",
            K.UseAgentBroker => "UseAgentBroker",

            K.Test1 => "TestSetting1",
            K.Test2 => "TestSetting2",
            K.Test3 => "Test.Settings_with",
            K.Test4 => "TestSettingEntry With A  Space",
            K.Test5 => "ª",
            K.Test6 => "VeryVeryLongTestSettingEntrySoTheClassCanReallyBeStressedOut",
            K.Test7_Legacy => "LegacyBoolSetting",
            K.Unset => throw new InvalidDataException("Setting key was unset!"),
            _ => throw new KeyNotFoundException(
                $"The settings key {key} was not found on the ResolveKey map"
            ),
        };
    }
}
