blank_issues_enabled: false

contact_links:
  - name: 📦 ISSUES INSTALLING/UPDATING A PACKAGE
    url: https://github.com/Devolutions/UniGetUI
    about: PLEASE READ THIS BEFORE CREATING AN ISSUE RELATED TO A SPECIFIC PACKAGE
  - name: 🔒 Security issue or vulnerability
    url: https://devolutions.net/security/
    about: Found a security issue? Please report it via the Devolutions security page
  - name: 📧 Contact us directly, in private
    url: https://devolutions.net/contact/
    about: Please use only for private inquiries that should not be posted publicly
